// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOl5Svg6iXSvThR88_MPFtyYr_dT5vN4E',
    appId: '1:935753044105:web:8b6ed4dc4bf5cc758f3658',
    messagingSenderId: '935753044105',
    projectId: 'madfinal-1b64e',
    authDomain: 'madfinal-1b64e.firebaseapp.com',
    storageBucket: 'madfinal-1b64e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-KhBB_eZ1ArGTjBiqKTraXZAyFgYo2ug',
    appId: '1:935753044105:android:db37710d210185a68f3658',
    messagingSenderId: '935753044105',
    projectId: 'madfinal-1b64e',
    storageBucket: 'madfinal-1b64e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHSCvEhbk8kRvuYVcYYvV8jlK4MbplZEs',
    appId: '1:935753044105:ios:294f4db4aafb9b7f8f3658',
    messagingSenderId: '935753044105',
    projectId: 'madfinal-1b64e',
    storageBucket: 'madfinal-1b64e.appspot.com',
    iosClientId: '935753044105-d6vrvlgi4tdlasd0528jp16mgfe59ps4.apps.googleusercontent.com',
    iosBundleId: 'com.example.madfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHSCvEhbk8kRvuYVcYYvV8jlK4MbplZEs',
    appId: '1:935753044105:ios:294f4db4aafb9b7f8f3658',
    messagingSenderId: '935753044105',
    projectId: 'madfinal-1b64e',
    storageBucket: 'madfinal-1b64e.appspot.com',
    iosClientId: '935753044105-d6vrvlgi4tdlasd0528jp16mgfe59ps4.apps.googleusercontent.com',
    iosBundleId: 'com.example.madfinal',
  );
}
